version: '3.8'

services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: "todo"
      POSTGRES_USER: "todouser"
      POSTGRES_PASSWORD: "todopsw"
    volumes:
      - ../db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todouser -d todo"]
      interval: 1s
      timeout: 3s
      retries: 5
      start_period: 10s

    
  backend:
    build: .
    privileged: true
    ports:
      - 8080:8080
    command: bash -c "
        python manage.py migrate &&
        gunicorn --bind 0.0.0.0:8000 todo.wsgi"
    depends_on:
      db:
        condition: service_healthy
    restart:
      always
      
      
  nginx:
    build: ./nginx
    ports: 
      - 8000:80
    depends_on:
      - backend
      
  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - nginx
